# Generated by Django 5.2.4 on 2025-10-17 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_contactmessage_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Full Stack AI Engineer', help_text='Your professional title', max_length=250)),
                ('bio', models.TextField(blank=True, default='Passionate about building intelligent solutions that solve real-world problems.', help_text='A short bio about yourself')),
                ('about_me', models.TextField(blank=True, default='I specialize in creating end-to-end AI solutions that are scalable, maintainable, and user-friendly.', help_text='Detailed information about you')),
                ('profile_image', models.ImageField(blank=True, help_text='Upload a professional profile picture', null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('github_url', models.URLField(blank=True, default='', verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, default='', verbose_name='LinkedIn URL')),
                ('twitter_url', models.URLField(blank=True, default='', verbose_name='Twitter URL')),
                ('portfolio_url', models.URLField(blank=True, default='', verbose_name='Portfolio URL')),
                ('email', models.EmailField(blank=True, default='', help_text='Your professional email', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.CharField(blank=True, default='', max_length=255)),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
