# Generated by Django 5.2.4 on 2025-10-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a professional profile picture (will be resized to 400x400)', null=True, upload_to='profile/'),
        ),
    ]
