# Generated by Django 5.2.4 on 2025-10-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('issuer', models.CharField(choices=[('coursera', 'Coursera'), ('edx', 'edX'), ('udacity', 'Udacity'), ('linkedin_learning', 'LinkedIn Learning'), ('deeplearning-ai', 'DeepLearning.AI'), ('other', 'Other')], max_length=50)),
                ('issuer_other', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_id', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('description', models.TextField()),
                ('skills', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issue_date', '-featured'],
            },
        ),
    ]
